# Generated by Django 3.2 on 2023-12-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='messenger',
            field=models.CharField(choices=[('TELEGRAM', 'Телеграм'), ('VK', 'Вконтакте')], max_length=16),
        ),
    ]
